### ISSUE TITLE
Error running foxx with nodist on Windows

### ISSUE THREAD

**Issue by Calrain** [arangodb/foxx-cli#11]
Running foxx-cli on a Windows Server 2016 machine with nodist installed.
https://github.com/marcelklehr/nodist

The error that comes up when running just the command `foxx` is:

    C:\Program Files (x86)\Nodist\bin\node_modules\foxx-cli\src\cmds\bundle.js:56
    exports.handler = async function handler(argv) {
                            ^^^^^^^^
    SyntaxError: Unexpected token function
        at Object.exports.runInThisContext (vm.js:76:16)
        at Module._compile (module.js:513:28)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\foxx-cli\src\index.js:21:12)
        at Module._compile (module.js:541:32)

This may be an issue with `nodist` more than `foxx-cli` but I thought worth logging.

**Comment by Calrain** [comment]
May be unrelated to foxx, closing until i can confirm it is.

**Comment by pluma** [comment]
That sounds like your node version is out of date. The current pre-release is written for more recent versions of node but the final release will be compiled for version 6 and above.
