### ISSUE TITLE
Not able to install new Foxx service on ArangoDB

### ISSUE THREAD

**Issue by ShaunLadd** [arangodb/foxx-cli#47]
Foxx CLI version 2.0.0
ArangoDB version 3.6.3

I am probably doing something wrong since this is the first time trying to install our Foxx service via the Foxx CLI.  To generate this error I did the following:

Cloned repository
Changed directory into where our Foxx service resides (myservice)
Performed an "npm install"
Then attempted to load the Foxx service to the database via this command:
foxx install --server https://testing.mydomain.co -u root -P /myservice

I received this error:

Sorry! An unexpected error occurred. This is likely a bug in foxx-cli.
Please open an issue at https://github.com/arangodb/foxx-cli/issues with a full copy of the following error message and a description of what you were trying to do when this problem occurred.

HttpError: Payload Too Large
    at new HttpError (/home/ec2-user/.nvm/versions/node/v15.0.1/lib/node_modules/foxx-cli/node_modules/arangojs/error.js:146:21)
    at Object.resolve (/home/ec2-user/.nvm/versions/node/v15.0.1/lib/node_modules/foxx-cli/node_modules/arangojs/connection.js:373:32)
    at callback (/home/ec2-user/.nvm/versions/node/v15.0.1/lib/node_modules/foxx-cli/node_modules/arangojs/connection.js:191:26)
    at IncomingMessage.<anonymous> (/home/ec2-user/.nvm/versions/node/v15.0.1/lib/node_modules/foxx-cli/node_modules/arangojs/lib/request.node.js:108:21)
    at IncomingMessage.emit (node:events:339:22)
    at endReadableNT (node:internal/streams/readable:1289:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)

We apologize for the inconvenience.

I tried adding node_modules/ to a .foxxignore file but then it fails because the service is looking for npm modules

**Comment by ShaunLadd** [comment]
I am not sure if it matters but this ArangoDB cluster is running on EKS and was created via the Kube Arango operator, version 1.0.3

**Comment by pluma** [comment]
The error is not from ArangoDB but from something in between, presumably a reverse proxy or load balancer. You might want to adjust your server's request payload size limit.

**Comment by pluma** [comment]
I'm closing this as not reproducible.
